version: 0.0
Resources:
  TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: "${TASK_DEFINITION}"
      LoadBalancerInfo:
        ContainerName: "${CONTAINER_NAME}"
        ContainerPort: 5000

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: "arn:aws:iam::345594584716:role/codebuild-term-role"
      # Add other necessary BuildProject properties here

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: "arn:aws:iam::345594584716:role/codebuild-term-role"
      # Add other necessary Pipeline properties here
